### PR TITLE
Uniswap v3 wrapper documentation

### PR DESCRIPTION
**Pull request by krisbitney**
This PR adds Uniswap v3 wrapper documentation.

### CODE REVIEW

**Comment by rihp** [comment]
Here are a few quick comments : 

This link is pointing to the main docs site and not to the v3 demo
- https://github.com/polywrap/documentation/blob/99f57245ee4aa2da4e2c7060ec7a1587f5636766/docs/uniswapv3/into.md?plain=1#L12

Here we could maybe list another quick example usecase of the univ3 polywrapper
- https://github.com/polywrap/documentation/blob/99f57245ee4aa2da4e2c7060ec7a1587f5636766/docs/uniswapv3/into.md?plain=1#L60

link seems to be broken here
- https://github.com/polywrap/documentation/blob/99f57245ee4aa2da4e2c7060ec7a1587f5636766/docs/uniswapv3/into.md?plain=1#L61

**Comment by krisbitney** [comment]
> Here are a few quick comments :
> 
> This link is pointing to the main docs site and not to the v3 demo
> 
> * https://github.com/polywrap/documentation/blob/99f57245ee4aa2da4e2c7060ec7a1587f5636766/docs/uniswapv3/into.md?plain=1#L12
> 
> Here we could maybe list another quick example usecase of the univ3 polywrapper
> 
> * https://github.com/polywrap/documentation/blob/99f57245ee4aa2da4e2c7060ec7a1587f5636766/docs/uniswapv3/into.md?plain=1#L60
> 
> link seems to be broken here
> 
> * https://github.com/polywrap/documentation/blob/99f57245ee4aa2da4e2c7060ec7a1587f5636766/docs/uniswapv3/into.md?plain=1#L61

Awesome feedback. Thanks! I added another use case example and fixed the source code link. For now, the demo link is pointing to the uniswap v2 demo. I'll update the v3 demo link once we have a live v3 demo.

**Comment by krisbitney** [comment]
> This looks really great @krisbitney, did you generate it with this? [polywrap/monorepo#428](https://github.com/polywrap/monorepo/pull/428)
> 
> Also do you think this PR ^^ is still a "draft"?

I generated it with [polywrap/monorepo#428], then manually sorted it into categories and put types in alphabetical order. The cli command can only distinguish between queries, mutations, types, and enums.

I recently made the command a draft again because I did some refactoring and added another output option (a styled docusaurus-based react app). I haven't pushed a commit yet because I had merged in the dapp command branch so the two commands could use the same folder structure, utility functions, etc.

And now that I think about it, I think it would be straightforward and easy to sort types alphabetically before outputting the docs, so I'll do that.

**Comment by dOrgJelli** [comment]
@krisbitney @rihp should we merge this since the wrapper is complete and published?

**Comment by krisbitney** [comment]
> @krisbitney @rihp should we merge this since the wrapper is complete and published?

I just made a minor change. You can merge it now if we are ready.

**Review by rihp — APPROVED** [review]
Amazing work, looking forward to see hundreds of usecases soon

**Pull request merged**
